site_name: Hackathon - Bitwars
theme: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - js/mathjax.js
